### ISSUE TITLE
Guzzle conflicts

### ISSUE THREAD

**Issue by textoo** [mailjet/wordpress-mailjet-plugin-apiv3#292]
Hello,

could it be possible to update the guzzle version ?
the actual is conflicting with other packages that are bundled with latest version. (for example mailjet-api itself)

```
Fatal error: Uncaught Error: Undefined class constant 'MAJOR_VERSION' in /var/www/vendor/guzzlehttp/guzzle/src/Utils.php:121


Stack trace:
--
  | #0 /var/www/vendor/guzzlehttp/guzzle/src/functions.php(71): GuzzleHttp\Utils::defaultUserAgent()
  | #1 /var/www/web/app/plugins/mailjet-for-wordpress/vendor/guzzlehttp/guzzle/src/Client.php(194): GuzzleHttp\default_user_agent()
  | #2 /var/www/web/app/plugins/mailjet-for-wordpress/vendor/guzzlehttp/guzzle/src/Client.php(75): GuzzleHttp\Client-&gt;configureDefaults(Array)
  | #3 /var/www/web/app/plugins/mailjet-for-wordpress/vendor/mailjet/mailjet-apiv3-php/src/Mailjet/Request.php(43): GuzzleHttp\Client-&gt;__construct(Array)
  | #4 /var/www/web/app/plugins/mailjet-for-wordpress/vendor/mailjet/mailjet-apiv3-php/src/Mailjet/Client.php(118): Mailjet\Request-&gt;__construct(Array, 'GET', 'http://api.mail...', Array, NULL, 'application/jso...', Array)
  | #5 /var/www/web/app/plugins/mailjet-for-wordpress/vendor/mailjet/mailjet-apiv3-php/src/Mailjet/Client.php(184): Mailjet\Client-&gt;_call('GET', 'contactmetadata', '', Ar in <b>/var/www/vendor/guzzlehttp/guzzle/src/Utils.php</b> on line <b>121</b><br />

```

thank you

**Comment by HansCz** [comment]
+1 for this

**Comment by agaleski** [comment]
+1 from me too
and fixing this soon would really help us saving time and resource on fixing this issue every time again after a plugin update ...

**Comment by agaleski** [comment]
Also I can confirm, that the plugin runs just fine with the latest guzzlehttp package ;)

**Comment by uavn** [comment]
Guzzle updated (with mailjet api sdk), will be rolled out with next plugin release
