### ISSUE TITLE
Wordpress Critical Error

### ISSUE THREAD

**Issue by mehmetnadir** [mailjet/wordpress-mailjet-plugin-apiv3#320]
I am getting a critical error warning, I have given the details below. I don't know what to do to solve the problem, can you help?

```
[28-Dec-2021 12:18:22 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function GuzzleHttp\choose_handler() in /public/wp-content/plugins/mailjet-for-wordpress/vendor/guzzlehttp/guzzle/src/HandlerStack.php:40
Stack trace:
#0 /public/wp-content/plugins/mailjet-for-wordpress/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()
#1 /public/wp-content/plugins/mailjet-for-wordpress/vendor/mailjet/mailjet-apiv3-php/src/Mailjet/Request.php(43): GuzzleHttp\Client->__construct()
#2 /public/wp-content/plugins/mailjet-for-wordpress/vendor/mailjet/mailjet-apiv3-php/src/Mailjet/Client.php(125): Mailjet\Request->__construct()
#3 /public/wp-content/plugins/mailjet-for-wordpress/vendor/mailjet/mailjet-apiv3-php/src/Mailjet/Client.php(188): Mailjet\Client->_call()
#4 /public/wp-content/plugins/mailjet-for-wordpress/src/includes/MailjetApi.php(364): Mailjet\Client->get()
#5 /public/wp-content/plugins/mailjet-for-wordpress/src/includes/MailjetSettings.php(196): MailjetPlugin\Includes\MailjetApi::isValidAPICredentials()
#6 /public/wp-content/plugins/mailjet-for-wordpress/src/includes/MailjetSettings.php(90): MailjetPlugin\Includes\MailjetSettings->addMailjetActions()
#7 /public/wp-includes/class-wp-hook.php(303): MailjetPlugin\Includes\MailjetSettings->mailjet_settings_init()
#8 /public/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#9 /public/wp-includes/plugin.php(470): WP_Hook->do_action()
#10 /public/wp-settings.php(578): do_action()
#11 /public/wp-config.php(47): require_once('...')
#12 /public/wp-load.php(50): require_once('...')
#13 /public/wp-admin/admin.php(34): require_once('...')
#14 {main}
  thrown in /public/wp-content/plugins/mailjet-for-wordpress/vendor/guzzlehttp/guzzle/src/HandlerStack.php on line 40
```

**Comment by eartisan-uk** [comment]
Any updates on this as this issue has still not been fixed?

**Comment by oleksandr-mykhailenko** [comment]
@mehmetnadir @eartisan-uk Hello. Could you provide more details, please ? When does it happen ? How I can reproduce the issue ?

**Comment by eartisan-uk** [comment]
@oleksandr-mykhailenko Sorry I gave up on this plugin and moved to a generic SMTP plugin, a few months ago.
